name: GitHub Actions Demo

on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]  # You can use 3.13.5 if supported, else use 3.12
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: ls -r ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}."
      
      # Instead of installing from requirements.txt, do it manually:
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install scikit-learn matplotlib

      - name: Run experiment
        run: python main.py